name: Scheduled and Manual Workflow

on:
  schedule:
    - cron: '*/1 * * * *'  # Run every 1 minute
  workflow_dispatch:       # Allows manual trigger

jobs:
  test_job:
    runs-on: ubuntu-latest

    steps:
      - name: Print the current time
        run: echo "The current time is $(date)"
