name: Run Every Minute

on:
  schedule:
    - cron: '*/1 * * * *'  # Runs every minute

jobs:
  test_job:
    runs-on: ubuntu-latest

    steps:
      - name: Print the current time
        run: echo "The current time is $(date)"
