name: Test Workflow

on:
  workflow_dispatch:  # Allows manual triggering

jobs:
  test_job:
    runs-on: ubuntu-latest

    steps:
      - name: Print a message
        run: echo "GitHub Actions are working!"
